# Configurações do banco de dados MySQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_springboot_persons
    username: root
    password: 12345

  # Configurações adicionais do Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false